from typing import Callable, Protocol

import numpy as np


class Viewer(Protocol):
    def build_from(self, mat: np.ndarray) -> None: ...
    def refresh(self, mat: np.ndarray) -> None: ...
    def set_pick_callback(self, fn: "Callable[[np.ndarray], None]") -> None: ...
    def show(self) -> None: ...
